### ISSUE TITLE
doesnt work for me at all

### ISSUE THREAD

**Issue by Xebtria** [Halkreen/poe-secondscreen#4]
All I can do is create new leveling. it imports my pob that's all fine.

![](https://i.imgur.com/10AMVKA.png)

I immediately see that it doesnt start at the correct level. it somehow thinks I am already lvl 28 or higher?
it doesnt progress when I level up, neither by actually leveling up, nor by faking it via manually editing the client.txt.

my PoB is set up correctly (I think):
![](https://i.imgur.com/yIeMiTx.png)
I also have only one tree there (tree is importet correctly, this works.

Also I saw that the link colors are not correct even though I have set dummy weapons with the correct link colors in my pob and added all the gems setups to their correct setup.

that's my full pob if you want to check: https://pastebin.com/9C6dM8Ec

I would love to attach the json file but I do not know where to find it. or is there no json when I import a pob?

edit:
I just found the other folder in appdata/roaming, but there is only a config.json, which looks like this
![](https://i.imgur.com/c0ma7jT.png)
I dont think that is the json of my build.
before you ask, yes the character names are correct, I tend to do that when I just test stuff.

**Comment by Halkreen** [comment]
Hello and thank you for reaching out !

I found 2 bugs there:
- First: your leveling PoB **has to** start at level 1, like your character. I will add it to the README
- Second: the sockeet color bug was found in the code and I push https://github.com/Halkreen/poe-secondscreen/commit/a008c24cc5f1ac1d9986df3000344a5ded9a4517 to fix it. Path of Building exports gems as "Elemental Proliferation" instead of "Elemental Proliferation **Support**" so I changed the socket indexing accordingly. I'll be releasing 1.2.2 to fix this bug, stay tuned !

**Comment by Halkreen** [comment]
Should be fixed in https://github.com/Halkreen/poe-secondscreen/releases/tag/v1.2.2

Closing the issue, thank you !

**Comment by Xebtria** [comment]
seems to work for me now, just need to add that the leveling did not work first, but then I read this part in the readme "(don't forget the client.txt part !)" and that fixed it. I hope this makes it a bit easier for me than to switch back and forth between multiple tabs in the PoB now, that'd be awesome, thanks! 

(oh and just as a note, accessing the options from somewhere other than "new leveling" or writing directly into the config.json would be nice :D just saying
